// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NganHangCauHoi.Data.Models;

namespace NganHangCauHoi.Data.Migrations
{
    [DbContext(typeof(NganHangCauHoiDataContext))]
    [Migration("20220622071747_nhch002")]
    partial class nhch002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_BoCauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdHocPhan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TienTo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NHCH_BoCauHois");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_BoCauHoi_CauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdBoCauHoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCauHoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaBoCauHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCauHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NHCH_BoCauHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NHCH_BoCauHoiId");

                    b.ToTable("NHCH_BoCauHoi_CauHois");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_CauHoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdChuDe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHocPhan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMucDo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("KhaDung")
                        .HasColumnType("bit");

                    b.Property<string>("MaHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaMucDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungRutGon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STTCauHoi")
                        .HasColumnType("int");

                    b.Property<int>("TinChi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NHCH_CauHois");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_CauHoi_Clo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdCauHoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdClo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NHCH_CauHoiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NHCH_CauHoiId");

                    b.ToTable("NHCH_CauHoi_Clos");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_ChuDe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdHocPhan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMucDo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucDo")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<int>("TinChi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NHCH_ChuDes");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_ChuDe_MucTieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdChuDe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdClo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NHCH_ChuDeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NHCH_ChuDeId");

                    b.ToTable("NHCH_ChuDe_MucTieus");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_Clo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NHCH_Clos");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_DeThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountOfApprove")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentWorkflowStep")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentWorkflowType")
                        .HasColumnType("int");

                    b.Property<Guid?>("FileApprovedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdBoCauHoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCaThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDotThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHocKy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHocPhan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLichThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMaTranDeThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNamHoc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdToChucThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaDotThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MetadataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayThi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiGianLamBai")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCountOfApprove")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NHCH_DeThis");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_DeThi_ChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Diem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdCauHoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDeThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMaTranDeThiChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NHCH_DeThiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NHCH_DeThiId");

                    b.ToTable("NHCH_DeThi_ChiTiets");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MaTranDeThi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdHocPhan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TienTo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NHCH_MaTranDeThis");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MaTranDeThi_ChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdChuDe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMaTranDeThi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMucDo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NHCH_MaTranDeThiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<int>("TinChi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NHCH_MaTranDeThiId");

                    b.ToTable("NHCH_MaTranDeThi_ChiTiets");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MucDo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucDo")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NHCH_MucDos");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MucTieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NHCH_MucTieus");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MucTieu_Clo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdClo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMucTieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaClo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NHCH_MucTieuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NHCH_MucTieuId");

                    b.ToTable("NHCH_MucTieu_Clos");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.WorkflowPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowEdit")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HemisCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HemisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHistory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotInWorkflow")
                        .HasColumnType("bit");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<int?>("PersistedId")
                        .HasColumnType("int");

                    b.Property<string>("RoleIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Synced")
                        .HasColumnType("bit");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextTrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserIdCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdsCombine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowPermission", "dbo");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_BoCauHoi_CauHoi", b =>
                {
                    b.HasOne("NganHangCauHoi.Data.Models.NHCH_BoCauHoi", "NHCH_BoCauHoi")
                        .WithMany("NHCH_BoCauHoi_CauHois")
                        .HasForeignKey("NHCH_BoCauHoiId");

                    b.Navigation("NHCH_BoCauHoi");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_CauHoi_Clo", b =>
                {
                    b.HasOne("NganHangCauHoi.Data.Models.NHCH_CauHoi", "NHCH_CauHoi")
                        .WithMany("NHCH_CauHoi_Clos")
                        .HasForeignKey("NHCH_CauHoiId");

                    b.Navigation("NHCH_CauHoi");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_ChuDe_MucTieu", b =>
                {
                    b.HasOne("NganHangCauHoi.Data.Models.NHCH_ChuDe", "NHCH_ChuDe")
                        .WithMany("NHCH_ChuDe_MucTieus")
                        .HasForeignKey("NHCH_ChuDeId");

                    b.Navigation("NHCH_ChuDe");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_DeThi_ChiTiet", b =>
                {
                    b.HasOne("NganHangCauHoi.Data.Models.NHCH_DeThi", "NHCH_DeThi")
                        .WithMany("NHCH_DeThi_ChiTiets")
                        .HasForeignKey("NHCH_DeThiId");

                    b.Navigation("NHCH_DeThi");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MaTranDeThi_ChiTiet", b =>
                {
                    b.HasOne("NganHangCauHoi.Data.Models.NHCH_MaTranDeThi", "NHCH_MaTranDeThi")
                        .WithMany("NHCH_MaTranDeThi_ChiTiets")
                        .HasForeignKey("NHCH_MaTranDeThiId");

                    b.Navigation("NHCH_MaTranDeThi");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MucTieu_Clo", b =>
                {
                    b.HasOne("NganHangCauHoi.Data.Models.NHCH_MucTieu", "NHCH_MucTieu")
                        .WithMany("NHCH_MucTieu_Clos")
                        .HasForeignKey("NHCH_MucTieuId");

                    b.Navigation("NHCH_MucTieu");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_BoCauHoi", b =>
                {
                    b.Navigation("NHCH_BoCauHoi_CauHois");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_CauHoi", b =>
                {
                    b.Navigation("NHCH_CauHoi_Clos");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_ChuDe", b =>
                {
                    b.Navigation("NHCH_ChuDe_MucTieus");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_DeThi", b =>
                {
                    b.Navigation("NHCH_DeThi_ChiTiets");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MaTranDeThi", b =>
                {
                    b.Navigation("NHCH_MaTranDeThi_ChiTiets");
                });

            modelBuilder.Entity("NganHangCauHoi.Data.Models.NHCH_MucTieu", b =>
                {
                    b.Navigation("NHCH_MucTieu_Clos");
                });
#pragma warning restore 612, 618
        }
    }
}
