FROM dockerhub.dttt.vn/aspnetcore-with-grpc:5.2-debug
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./bin/Debug/netcoreapp5.0/publish_debug /app
ENTRYPOINT ["/usr/bin/supervisord"]
